[package]
name = "Win-Set-AudioOUT"
version = "1.0.0"
edition = "2021"
build = "build.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tempfile = "3.3.0"

[build-dependencies]
winres = "0.1.12"
